# Generated by Django 4.1 on 2024-03-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tenant',
        ),
    ]
