# Generated by Django 4.1 on 2024-03-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(null=True, upload_to='users/employer')),
                ('expected_salary', models.PositiveIntegerField()),
                ('profession_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer', to='experience.professioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerHaveSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.skills')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='skills',
            field=models.ManyToManyField(related_name='employers', through='employer.EmployerHaveSkills', to='experience.skills'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
