# Generated by Django 4.1 on 2024-03-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='github',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
